### PR TITLE
Added serialize_functions.js

### PR DESCRIPTION
**Pull request by Ratstail91**
This seems to be something that several people were interested in, despite it's apparent inefficiency.

Efficiency wasn't the goal - a unique solution was.

Documentation was added in the comment header.

### CODE REVIEW

**Comment by rebelzach** [comment]
👍 for contributing. In javascript creating a function from the name doesn't always do what you think. 

See this SO question for reference. https://stackoverflow.com/questions/359788/how-to-execute-a-javascript-function-when-i-have-its-name-as-a-string 

Maybe this could become a note about how to serialize information for doing a callback in Screeps.

**Comment by Ratstail91** [comment]
I should've also mentioned that this only works for anonymous functions - so functions created with the arrow operator. Here's an example of it working.

```js
let onSafe = serializeFunction(creep => {
	creep.memory['HARVEST'].remote = null;
	creep.memory['HARVEST'].source = null;
});```

I'm actually using it here: https://github.com/Ratstail91/screeps/blob/master/dist/spawns.spawners.js?ts=4#L12

**Comment by RvstFyth** [comment]
> I should've also mentioned that this only works for anonymous functions

That is not true, it should also work with 

```js
function a () {
	console.log(123);
}
const b = serializeFunction(a);
const c = deserializeFunction(b);
c();
```

**Comment by Ratstail91** [comment]
Well that sucks. I didn't realize you could vote now.

**Comment by tedivm** [comment]
With the way the current rules are it wouldn't have mattered- since you need 75% approval to pass it takes three positive votes to override a single negative, meaning this would have needed another seven positive votes to get merged.

**Comment by Ratstail91** [comment]
Well I'll take my snippet and go home then...

**Pull request closed without merging**
